version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - forcetypeassert
    - godot
    - govet
    - gocritic
    - ineffassign
    - makezero
    - misspell
    - gosec
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - exhaustive
    - iface
    - nolintlint
    - unconvert
    - goconst
    - whitespace
    - exptostd
    - gocheckcompilerdirectives
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/piano_publisher/PianoPublisherClient.go
      - third_party$
      - builtin$
      - examples$
  settings:
    misspell:
      ignore-rules:
        - copywrite # The name of CLI tool
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
