# Copyright (c) Yoichiro Ito <contact.110416@gmail.com>
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: id
  version: SNAPSHOT
servers:
  - url: /id/api/v1
paths:
  /publisher/customField:
    post:
      summary: "create or update one or more custom field keys"
      description: >-
        create or update one or more custom field keys
      operationId: PublisherCustomFieldPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPublisherCustomFieldRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPublisherCustomFieldResponse'
          required: true
        default:
          description: default response(error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PianoIDErrorDetail'
components:
  schemas:
    PostPublisherCustomFieldRequest:
      type: array
      items:
        $ref: '#/components/schemas/CustomFieldDefinition'
        required: true
    PostPublisherCustomFieldResponse:
      type: array
      items:
        $ref: '#/components/schemas/CustomFieldDefinition'
        required: true
    PianoIDErrorDetail:
      type: object
      required:
        - error_code_list
      properties:
        error_code_list:
          type: array
          items:
            $ref: '#/components/schemas/PianoIDErrorDetailItem'
    PianoIDErrorDetailItem:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    CustomFieldDefinition:
      type: object
      required:
        - field_name
        - title
        - comment
        - editable
        - data_type
        - options
        - required_by_default
        - archived
        - default_sort_order
        - attribute
        - validators
      properties:
        field_name:
          type: string
          description: |
            The field name of this custom field.
            This value serves as an identifier for the field.
        title:
          type: string
          description: |
            The title of this field. This field is visible to users.
        comment:
          type: string
          nullable: true
          description: |
            The internal comment about this field. This is NOT visible to users.
        editable:
          type: boolean
        data_type:
          type: string
          enum:
            - TEXT
            - ISO_DATE
            - BOOLEAN
            - SINGLE_SELECT_LIST
            - MULTI_SELECT_LIST
        options:
          type: array
          items:
            type: string
        required_by_default:
          type: boolean
        archived:
          type: boolean
          description: |
            Whether or not this field is archived.
        default_sort_order:
          type: integer
          format: int32
          nullable: true
        attribute:
          $ref: '#/components/schemas/CustomFieldAttribute'
          nullable: true
        tooltip:
          $ref: '#/components/schemas/Tooltip'
          nullable: true
        validators:
          description: |
            This value must not be null in every request.
            Without this field, server ends up with internal server error.
          type: array
          items:
            $ref: "#/components/schemas/Validator"
        favourite_options:
          description: |
            Extra options for the field.
            - "prechecked": check the checkbox(Boolean field) by default
          type: array
          items:
            type: string
            enum:
              - "prechecked"
    CustomFieldAttribute:
      type: object
      properties:
        default_value:
          type: string
          nullable: true
          description: The default value for this field.
        placeholder:
          type: string
          nullable: true
          description: The placeholder of this field. Avaiable for TEXT or SINGLE_SELECT_LIST field
        multiline:
          description: Whether or not the TEXT field allows multiline input
          type: boolean
        date_format:
          type: string
          nullable: true
          description: "The format of ISO_DATE field. Default is null"
          enum:
            - mm/dd/yyyy
            - mm.dd.yyyy
            - dd/mm/yyyy
            - dd.mm.yyyy
            - yyyy/mm/dd
            - yyyy.mm.dd
            - yyyy/dd/mm
            - yyyy.dd.mm
        pre_select_country_by_ip:
          type: boolean
          description: Whether or not select country by ip for country field. Default is false.
        global:
          type: boolean
          description: Whether or not this field is a global field. Default is false.
    Tooltip:
      type: object
      properties:
        type:
          type: string
        enabled:
          type: boolean
        text:
          type: string
    Validator:
      type: object
      required:
        - type
        - params
        - errorMessage
      properties:
        type:
          type: string
          enum:
            - STR_LENGTH
            - REGEXP
            - EMAIL
            - WHITELIST
            - BLACKLIST
        params:
          $ref: "#/components/schemas/ValidatorParameter"
        errorMessage:
          type: string
          description: Error message field __for request__
          nullable: true
        error_message:
          type: string
          description: Error message field __for response__
          nullable: true
          x-go-name: ReponseErrorMessage
    ValidatorParameter:
      type: object
      properties:
        minLength:
          type: integer
          description: The min length of text for STR_LENGTH validator
          format: int32
        maxLength:
          type: integer
          format: int32
          description: The max length of text for STR_LENGTH validator
        regexp:
          type: string
          description: The regular expression for REGEXP validator
        whitelist:
          type: array
          description: The list of string for WHITELIST validator
          items:
            type: string
        blacklist:
          type: array
          items:
            type: string
          description: The list of string for BLACKLIST validator