// Package piano_id provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package piano_id

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for CustomFieldAttributeDateFormat.
const (
	DdMmYyyy CustomFieldAttributeDateFormat = "dd.mm.yyyy"
	Ddmmyyyy CustomFieldAttributeDateFormat = "dd/mm/yyyy"
	MmDdYyyy CustomFieldAttributeDateFormat = "mm.dd.yyyy"
	Mmddyyyy CustomFieldAttributeDateFormat = "mm/dd/yyyy"
	YyyyDdMm CustomFieldAttributeDateFormat = "yyyy.dd.mm"
	YyyyMmDd CustomFieldAttributeDateFormat = "yyyy.mm.dd"
	Yyyyddmm CustomFieldAttributeDateFormat = "yyyy/dd/mm"
	Yyyymmdd CustomFieldAttributeDateFormat = "yyyy/mm/dd"
)

// Defines values for CustomFieldDefinitionDataType.
const (
	BOOLEAN          CustomFieldDefinitionDataType = "BOOLEAN"
	ISODATE          CustomFieldDefinitionDataType = "ISO_DATE"
	MULTISELECTLIST  CustomFieldDefinitionDataType = "MULTI_SELECT_LIST"
	SINGLESELECTLIST CustomFieldDefinitionDataType = "SINGLE_SELECT_LIST"
	TEXT             CustomFieldDefinitionDataType = "TEXT"
)

// Defines values for CustomFieldDefinitionFavouriteOptions.
const (
	Prechecked CustomFieldDefinitionFavouriteOptions = "prechecked"
)

// Defines values for ValidatorType.
const (
	BLACKLIST ValidatorType = "BLACKLIST"
	EMAIL     ValidatorType = "EMAIL"
	REGEXP    ValidatorType = "REGEXP"
	STRLENGTH ValidatorType = "STR_LENGTH"
	WHITELIST ValidatorType = "WHITELIST"
)

// CustomFieldAttribute defines model for CustomFieldAttribute.
type CustomFieldAttribute struct {
	// DateFormat The format of ISO_DATE field. Default is null
	DateFormat *CustomFieldAttributeDateFormat `json:"date_format"`

	// DefaultValue The default value for this field.
	DefaultValue *string `json:"default_value"`

	// Global Whether or not this field is a global field. Default is false.
	Global *bool `json:"global,omitempty"`

	// Multiline Whether or not the TEXT field allows multiline input
	Multiline *bool `json:"multiline,omitempty"`

	// Placeholder The placeholder of this field. Avaiable for TEXT or SINGLE_SELECT_LIST field
	Placeholder *string `json:"placeholder"`

	// PreSelectCountryByIp Whether or not select country by ip for country field. Default is false.
	PreSelectCountryByIp *bool `json:"pre_select_country_by_ip,omitempty"`
}

// CustomFieldAttributeDateFormat The format of ISO_DATE field. Default is null
type CustomFieldAttributeDateFormat string

// CustomFieldDefinition defines model for CustomFieldDefinition.
type CustomFieldDefinition struct {
	// Archived Whether or not this field is archived.
	Archived  bool                 `json:"archived"`
	Attribute CustomFieldAttribute `json:"attribute"`

	// Comment The internal comment about this field. This is NOT visible to users.
	Comment          *string                       `json:"comment"`
	DataType         CustomFieldDefinitionDataType `json:"data_type"`
	DefaultSortOrder *int32                        `json:"default_sort_order"`
	Editable         bool                          `json:"editable"`

	// FavouriteOptions Extra options for the field.
	// - "prechecked": check the checkbox(Boolean field) by default
	FavouriteOptions *[]CustomFieldDefinitionFavouriteOptions `json:"favourite_options,omitempty"`

	// FieldName The field name of this custom field.
	// This value serves as an identifier for the field.
	FieldName         string   `json:"field_name"`
	Options           []string `json:"options"`
	RequiredByDefault bool     `json:"required_by_default"`

	// Title The title of this field. This field is visible to users.
	Title   string   `json:"title"`
	Tooltip *Tooltip `json:"tooltip,omitempty"`

	// Validators This value must not be null in every request.
	// Without this field, server ends up with internal server error.
	Validators []Validator `json:"validators"`
}

// CustomFieldDefinitionDataType defines model for CustomFieldDefinition.DataType.
type CustomFieldDefinitionDataType string

// CustomFieldDefinitionFavouriteOptions defines model for CustomFieldDefinition.FavouriteOptions.
type CustomFieldDefinitionFavouriteOptions string

// PianoIDErrorDetail defines model for PianoIDErrorDetail.
type PianoIDErrorDetail struct {
	ErrorCodeList []PianoIDErrorDetailItem `json:"error_code_list"`
}

// PianoIDErrorDetailItem defines model for PianoIDErrorDetailItem.
type PianoIDErrorDetailItem struct {
	Message string `json:"message"`
}

// PostPublisherCustomFieldRequest defines model for PostPublisherCustomFieldRequest.
type PostPublisherCustomFieldRequest = []CustomFieldDefinition

// PostPublisherCustomFieldResponse defines model for PostPublisherCustomFieldResponse.
type PostPublisherCustomFieldResponse = []CustomFieldDefinition

// Tooltip defines model for Tooltip.
type Tooltip struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Text    *string `json:"text,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// Validator defines model for Validator.
type Validator struct {
	// ErrorMessage Error message field __for request__
	ErrorMessage *string `json:"errorMessage"`

	// ReponseErrorMessage Error message field __for response__
	ReponseErrorMessage *string            `json:"error_message"`
	Params              ValidatorParameter `json:"params"`
	Type                ValidatorType      `json:"type"`
}

// ValidatorType defines model for Validator.Type.
type ValidatorType string

// ValidatorParameter defines model for ValidatorParameter.
type ValidatorParameter struct {
	// Blacklist The list of string for BLACKLIST validator
	Blacklist *[]string `json:"blacklist,omitempty"`

	// MaxLength The max length of text for STR_LENGTH validator
	MaxLength *int32 `json:"maxLength,omitempty"`

	// MinLength The min length of text for STR_LENGTH validator
	MinLength *int32 `json:"minLength,omitempty"`

	// Regexp The regular expression for REGEXP validator
	Regexp *string `json:"regexp,omitempty"`

	// Whitelist The list of string for WHITELIST validator
	Whitelist *[]string `json:"whitelist,omitempty"`
}

// PublisherCustomFieldPostJSONRequestBody defines body for PublisherCustomFieldPost for application/json ContentType.
type PublisherCustomFieldPostJSONRequestBody = PostPublisherCustomFieldRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublisherCustomFieldPostWithBody request with any body
	PublisherCustomFieldPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublisherCustomFieldPost(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublisherCustomFieldPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublisherCustomFieldPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublisherCustomFieldPost(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublisherCustomFieldPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublisherCustomFieldPostRequest calls the generic PublisherCustomFieldPost builder with application/json body
func NewPublisherCustomFieldPostRequest(server string, body PublisherCustomFieldPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublisherCustomFieldPostRequestWithBody(server, "application/json", bodyReader)
}

// NewPublisherCustomFieldPostRequestWithBody generates requests for PublisherCustomFieldPost with any type of body
func NewPublisherCustomFieldPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/publisher/customField")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublisherCustomFieldPostWithBodyWithResponse request with any body
	PublisherCustomFieldPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error)

	PublisherCustomFieldPostWithResponse(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error)
}

type PublisherCustomFieldPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostPublisherCustomFieldResponse
	JSONDefault  *PianoIDErrorDetail
}

// Status returns HTTPResponse.Status
func (r PublisherCustomFieldPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublisherCustomFieldPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PublisherCustomFieldPostWithBodyWithResponse request with arbitrary body returning *PublisherCustomFieldPostResponse
func (c *ClientWithResponses) PublisherCustomFieldPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error) {
	rsp, err := c.PublisherCustomFieldPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublisherCustomFieldPostResponse(rsp)
}

func (c *ClientWithResponses) PublisherCustomFieldPostWithResponse(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error) {
	rsp, err := c.PublisherCustomFieldPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublisherCustomFieldPostResponse(rsp)
}

// ParsePublisherCustomFieldPostResponse parses an HTTP response from a PublisherCustomFieldPostWithResponse call
func ParsePublisherCustomFieldPostResponse(rsp *http.Response) (*PublisherCustomFieldPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublisherCustomFieldPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostPublisherCustomFieldResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest PianoIDErrorDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
