// Package piano_id provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package piano_id

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for CustomFieldDefinitionDataType.
const (
	CustomFieldDefinitionDataTypeBOOLEAN          CustomFieldDefinitionDataType = "BOOLEAN"
	CustomFieldDefinitionDataTypeISODATE          CustomFieldDefinitionDataType = "ISO_DATE"
	CustomFieldDefinitionDataTypeMULTISELECTLIST  CustomFieldDefinitionDataType = "MULTI_SELECT_LIST"
	CustomFieldDefinitionDataTypeSINGLESELECTLIST CustomFieldDefinitionDataType = "SINGLE_SELECT_LIST"
	CustomFieldDefinitionDataTypeTEXT             CustomFieldDefinitionDataType = "TEXT"
)

// Defines values for PostPublisherCustomFieldResponseItemDataType.
const (
	PostPublisherCustomFieldResponseItemDataTypeBOOLEAN          PostPublisherCustomFieldResponseItemDataType = "BOOLEAN"
	PostPublisherCustomFieldResponseItemDataTypeISODATE          PostPublisherCustomFieldResponseItemDataType = "ISO_DATE"
	PostPublisherCustomFieldResponseItemDataTypeMULTISELECTLIST  PostPublisherCustomFieldResponseItemDataType = "MULTI_SELECT_LIST"
	PostPublisherCustomFieldResponseItemDataTypeSINGLESELECTLIST PostPublisherCustomFieldResponseItemDataType = "SINGLE_SELECT_LIST"
	PostPublisherCustomFieldResponseItemDataTypeTEXT             PostPublisherCustomFieldResponseItemDataType = "TEXT"
)

// CustomFieldDefinition defines model for CustomFieldDefinition.
type CustomFieldDefinition struct {
	Archived  bool                          `json:"archived"`
	Comment   *string                       `json:"comment"`
	DataType  CustomFieldDefinitionDataType `json:"data_type"`
	Editable  bool                          `json:"editable"`
	FieldName string                        `json:"field_name"`
	Title     string                        `json:"title"`
}

// CustomFieldDefinitionDataType defines model for CustomFieldDefinition.DataType.
type CustomFieldDefinitionDataType string

// PostPublisherCustomFieldRequest defines model for PostPublisherCustomFieldRequest.
type PostPublisherCustomFieldRequest = []CustomFieldDefinition

// PostPublisherCustomFieldResponse defines model for PostPublisherCustomFieldResponse.
type PostPublisherCustomFieldResponse = []PostPublisherCustomFieldResponseItem

// PostPublisherCustomFieldResponseItem defines model for PostPublisherCustomFieldResponseItem.
type PostPublisherCustomFieldResponseItem struct {
	Archived  bool                                         `json:"archived"`
	Comment   *string                                      `json:"comment"`
	Created   string                                       `json:"created"`
	DataType  PostPublisherCustomFieldResponseItemDataType `json:"dataType"`
	Editable  bool                                         `json:"editable"`
	FieldName string                                       `json:"fieldName"`
	Title     string                                       `json:"title"`
}

// PostPublisherCustomFieldResponseItemDataType defines model for PostPublisherCustomFieldResponseItem.DataType.
type PostPublisherCustomFieldResponseItemDataType string

// PublisherCustomFieldPostJSONRequestBody defines body for PublisherCustomFieldPost for application/json ContentType.
type PublisherCustomFieldPostJSONRequestBody = PostPublisherCustomFieldRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublisherCustomFieldPostWithBody request with any body
	PublisherCustomFieldPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublisherCustomFieldPost(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublisherCustomFieldPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublisherCustomFieldPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublisherCustomFieldPost(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublisherCustomFieldPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublisherCustomFieldPostRequest calls the generic PublisherCustomFieldPost builder with application/json body
func NewPublisherCustomFieldPostRequest(server string, body PublisherCustomFieldPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublisherCustomFieldPostRequestWithBody(server, "application/json", bodyReader)
}

// NewPublisherCustomFieldPostRequestWithBody generates requests for PublisherCustomFieldPost with any type of body
func NewPublisherCustomFieldPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/publisher/customField")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublisherCustomFieldPostWithBodyWithResponse request with any body
	PublisherCustomFieldPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error)

	PublisherCustomFieldPostWithResponse(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error)
}

type PublisherCustomFieldPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostPublisherCustomFieldResponse
}

// Status returns HTTPResponse.Status
func (r PublisherCustomFieldPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublisherCustomFieldPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PublisherCustomFieldPostWithBodyWithResponse request with arbitrary body returning *PublisherCustomFieldPostResponse
func (c *ClientWithResponses) PublisherCustomFieldPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error) {
	rsp, err := c.PublisherCustomFieldPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublisherCustomFieldPostResponse(rsp)
}

func (c *ClientWithResponses) PublisherCustomFieldPostWithResponse(ctx context.Context, body PublisherCustomFieldPostJSONRequestBody, reqEditors ...RequestEditorFn) (*PublisherCustomFieldPostResponse, error) {
	rsp, err := c.PublisherCustomFieldPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublisherCustomFieldPostResponse(rsp)
}

// ParsePublisherCustomFieldPostResponse parses an HTTP response from a PublisherCustomFieldPostWithResponse call
func ParsePublisherCustomFieldPostResponse(rsp *http.Response) (*PublisherCustomFieldPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublisherCustomFieldPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostPublisherCustomFieldResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
